const data = {
    products: [
      {
        name: 'productA-name',
        category: 'Pharma',
        description: 'asda',
        price: 100,
        token: 'productA-token',
        brand: 'Teva',
        countInStock: 6,
        rating: 2.5,
        numReviews: 100,
        image: '/images/p1.jpg',
      },
      {
        name: 'productB-name',
        category: 'Pharma',
        description: 'hhhh',
        price: 170,
        token: 'productB-token',
        brand: 'Teva',
        countInStock: 3,
        rating: 3,
        numReviews: 95,
        image: '/images/p2.jpg',
      },
      {
        name: 'productC-name',
        category: 'Pharma',
        description: 'gg',
        price: 70,
        token: 'productC-token',
        brand: 'Teva',
        countInStock: 24,
        rating: 4,
        numReviews: 120,
        image: '/images/p3.jpg',
      },
      {
        name: 'productD-name',
        category: 'Pharma',
        description: 'sss',
        price: 110,
        token: 'productD-token',
        brand: 'Teva',
        countInStock: 7,
        rating: 4.5,
        numReviews: 80,
        image: '/images/p4.jpg',
      },
  
  
  
      
      {
        name: 'productW-name',
        category: 'Pharma',
        description: 'sad',
        price: 100,
        token: 'productW-token',
        brand: 'Teva',
        countInStock: 6,
        rating: 2.5,
        numReviews: 100,
        image: '/images/p1.jpg',
      },
      {
        name: 'productO-name',
        category: 'Pharma',
        description: 'asdasd',
        price: 170,
        token: 'productO-token',
        brand: 'Teva',
        countInStock: 3,
        rating: 3,
        numReviews: 95,
        image: '/images/p2.jpg',
      },
      {
        name: 'productF-name',
        category: 'Pharma',
        description: '...',
        price: 70,
        token: 'productF-token',
        brand: 'Teva',
        countInStock: 24,
        rating: 4,
        numReviews: 120,
        image: '/images/p3.jpg',
      },
      {
        name: 'productL-name',
        category: 'Pharma',
        description: '...',
        price: 110,
        token: 'productL-token',
        brand: 'Teva',
        countInStock: 7,
        rating: 4.5,
        numReviews: 80,
        image: '/images/p4.jpg',
      },
    ],
  };
  
  export default data;
  